# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 834e0092110271dcecbf28c9104a15f5c91cceaf0f944bc03134818c1f0fa9013f2d6d6ceaff0a1134df9aa219684d42e9c6246667f303f734d85ae94bd1bbf0

test:
  secret_key_base: 5dda401f7a86b689987f2170638330323bf226bbdd0bbd9446d44343dcde1278b5c3060d9831ef9d11980d0ccc3673ba7a739b95498e180eaf54cbf3762d23d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
